/******************************************************************************
 * am335x.h
 *
 * Processor hardware defines for the am335x
 *
 * Paul Quevedo 2012
 *****************************************************************************/
#ifndef __AM335X_H__
#define __AM335X_H__

#include "globalDefs.h"
#define HWREG32(addr) (*(volatile uint32_t *) (addr))
#define HWREG16(addr) (*(volatile uint16_t *) (addr))
#define HWREG8 (addr) (*(volatile uint8_t  *) (addr))

/************************  WATCHDOG  *****************************************/
#define WDT_BASE_ADDR 0x44E35000
#define WDT_WIDR        HWREG32(WDT_BASE_ADDR + 0x00)
#define WDT_WDSC        HWREG32(WDT_BASE_ADDR + 0x10)
#define WDT_WDST        HWREG32(WDT_BASE_ADDR + 0x14)
#define WDT_WISR        HWREG32(WDT_BASE_ADDR + 0x18)
#define WDT_WIER        HWREG32(WDT_BASE_ADDR + 0x1C)
#define WDT_WCLR        HWREG32(WDT_BASE_ADDR + 0x24)
#define WDT_WCRR        HWREG32(WDT_BASE_ADDR + 0x28)
#define WDT_WLDR        HWREG32(WDT_BASE_ADDR + 0x2C)
#define WDT_WTGR        HWREG32(WDT_BASE_ADDR + 0x30)
#define WDT_WWPS        HWREG32(WDT_BASE_ADDR + 0x34)
#define WDT_WDLY        HWREG32(WDT_BASE_ADDR + 0x44)
#define WDT_WSPR        HWREG32(WDT_BASE_ADDR + 0x48)
#define WDT_WIRQSTATRAW HWREG32(WDT_BASE_ADDR + 0x54)
#define WDT_WIRQSTAT    HWREG32(WDT_BASE_ADDR + 0x58)
#define WDT_WIRQENSET   HWREG32(WDT_BASE_ADDR + 0x5C)
#define WDT_WIRQENCLR   HWREG32(WDT_BASE_ADDR + 0x60)

#define WDT_WWPS_W_PEND_WDLY    BIT_5 /* R   - 0 */
#define WDT_WWPS_W_PEND_WSPR    BIT_4 /* R   - 0 */
#define WDT_WWPS_W_PEND_WTGR    BIT_3 /* R   - 0 */
#define WDT_WWPS_W_PEND_WLDR    BIT_2 /* R   - 0 */
#define WDT_WWPS_W_PEND_WCRR    BIT_1 /* R   - 0 */
#define WDT_WWPS_W_PEND_WCLR    BIT_0 /* R   - 0 */

/******************** CLOCK MODULE PERIPHERALS *******************************/
#define CM_PER_BASE_ADDR 0x44E00000
#define CM_PER_L4LS_CLKSTCTRL      HWREG32(CM_PER_BASE_ADDR + 0x00)
#define CM_PER_L3S_CLKSTCTRL       HWREG32(CM_PER_BASE_ADDR + 0x04)
#define CM_PER_L4FW_CLKSTCTRL      HWREG32(CM_PER_BASE_ADDR + 0x08)
#define CM_PER_L3_CLKSTCTRL        HWREG32(CM_PER_BASE_ADDR + 0x0C)
#define CM_PER_CPGMAC0_CLKCTRL     HWREG32(CM_PER_BASE_ADDR + 0x14)
#define CM_PER_LCDC_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x18)
#define CM_PER_USB0_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x1C)
#define CM_PER_TPTC0_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x24)
#define CM_PER_EMIF_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x28)
#define CM_PER_OCMCRAM_CLKCTRL     HWREG32(CM_PER_BASE_ADDR + 0x2C)
#define CM_PER_GPMC_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x30)
#define CM_PER_MCASP0_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0x34)
#define CM_PER_UART5_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x38)
#define CM_PER_MMC0_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x3C)
#define CM_PER_ELM_CLKCTRL         HWREG32(CM_PER_BASE_ADDR + 0x40)
#define CM_PER_I2C2_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x44)
#define CM_PER_I2C1_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x48)
#define CM_PER_SPI0_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x4C)
#define CM_PER_SPI1_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x50)
#define CM_PER_L4LS_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x60)
#define CM_PER_L4FW_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x64)
#define CM_PER_MCASP1_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0x68)
#define CM_PER_UART1_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x6C)
#define CM_PER_UART2_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x70)
#define CM_PER_UART3_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x74)
#define CM_PER_UART4_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x78)
#define CM_PER_TIMER7_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0x7C)
#define CM_PER_TIMER2_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0x80)
#define CM_PER_TIMER3_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0x84)
#define CM_PER_TIMER4_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0x88)
#define CM_PER_GPIO1_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0xAC)
#define CM_PER_GPIO2_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0xB0)
#define CM_PER_GPIO3_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0xB4)
#define CM_PER_TPCC_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0xBC)
#define CM_PER_DCAN0_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0xC0)
#define CM_PER_DCAN1_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0xC4)
#define CM_PER_EPWMSS1_CLKCTRL     HWREG32(CM_PER_BASE_ADDR + 0xCC)
#define CM_PER_EMIF_FW_CLKCTRL     HWREG32(CM_PER_BASE_ADDR + 0xD0)
#define CM_PER_EPWMSS0_CLKCTRL     HWREG32(CM_PER_BASE_ADDR + 0xD4)
#define CM_PER_EPWMSS2_CLKCTRL     HWREG32(CM_PER_BASE_ADDR + 0xD8)
#define CM_PER_L3_INSTR_CLKCTRL    HWREG32(CM_PER_BASE_ADDR + 0xDC)
#define CM_PER_L3_CLKCTRL          HWREG32(CM_PER_BASE_ADDR + 0xE0)
#define CM_PER_IEEE5000_CLKCTRL    HWREG32(CM_PER_BASE_ADDR + 0xE4)
#define CM_PER_PRU_ICSS_CLKCTRL    HWREG32(CM_PER_BASE_ADDR + 0xE8)
#define CM_PER_TIMER5_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0xEC)
#define CM_PER_TIMER6_CLKCTRL      HWREG32(CM_PER_BASE_ADDR + 0xF0)
#define CM_PER_MMC1_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0xF4)
#define CM_PER_MMC2_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0xF8)
#define CM_PER_TPTC1_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0xFC)
#define CM_PER_TPTC2_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x100)
#define CM_PER_SPINLOCK_CLKCTRL    HWREG32(CM_PER_BASE_ADDR + 0x10C)
#define CM_PER_MAILBOX0_CLKCTRL    HWREG32(CM_PER_BASE_ADDR + 0x110)
#define CM_PER_L4HS_CLKSTCTRL      HWREG32(CM_PER_BASE_ADDR + 0x11C)
#define CM_PER_L4HS_CLKCTRL        HWREG32(CM_PER_BASE_ADDR + 0x120)
#define CM_PER_OCPWP_L3_CLKSTCT    HWREG32(CM_PER_BASE_ADDR + 0x12C)
#define CM_PER_OCPWP_CLKCTRL       HWREG32(CM_PER_BASE_ADDR + 0x130)
#define CM_PER_PRU_ICSS_CLKSTCTRL  HWREG32(CM_PER_BASE_ADDR + 0x140)
#define CM_PER_CPSW_CLKSTCTRL      HWREG32(CM_PER_BASE_ADDR + 0x144)
#define CM_PER_LCDC_CLKSTCTRL      HWREG32(CM_PER_BASE_ADDR + 0x148)
#define CM_PER_CLKDIV32K_CLKCTRL   HWREG32(CM_PER_BASE_ADDR + 0x14C)
#define CM_PER_CLK_24MHZ_CLKSTCTRL HWREG32(CM_PER_BASE_ADDR + 0x150)

/* CM_WKUP_CLKSTCTRL Bits */
#define CM_CLKACTIVITY_ADC_FCLK      BIT_14
#define CM_CLKACTIVITY_TIMER1_GCLK   BIT_13
#define CM_CLKACTIVITY_UART0_GFCLK   BIT_12
#define CM_CLKACTIVITY_I2C0_GFCLK    BIT_11
#define CM_CLKACTIVITY_TIMER0_GCLK   BIT_10
#define CM_CLKACTIVITY_GPIO0_GDBCLK  BIT_8
#define CM_CLKACTIVITY_WDT1_GCLK     BIT_4
#define CM_CLKACTIVITY_SR_SYSCLK     BIT_3
#define CM_CLKACTIVITY_L4_WKUP_GCLK  BIT_2

/* CM_PER_L4LS_CLKSTCTRL Bits */
#define CM_CLKACTIVITY_TIMER6_GCLK   BIT_28
#define CM_CLKACTIVITY_TIMER5_GCLK   BIT_27
#define CM_CLKACTIVITY_SPI_GCLK      BIT_25
#define CM_CLKACTIVITY_I2C_FCLK      BIT_24
#define CM_CLKACTIVITY_GPIO_3_GDBCLK BIT_21
#define CM_CLKACTIVITY_GPIO_2_GDBCLK BIT_20
#define CM_CLKACTIVITY_GPIO_1_GDBCLK BIT_19
#define CM_CLKACTIVITY_LCDC_GCLK     BIT_17
#define CM_CLKACTIVITY_TIMER4_GCLK   BIT_16
#define CM_CLKACTIVITY_TIMER3_GCLK   BIT_15
#define CM_CLKACTIVITY_TIMER2_GCLK   BIT_14
#define CM_CLKACTIVITY_TIMER7_GCLK   BIT_13
#define CM_CLKACTIVITY_CAN_CLK       BIT_11
#define CM_CLKACTIVITY_UART_GFCLK    BIT_10
#define CM_CLKACTIVITY_L4LS_GCLK     BIT_8

/* CM_PER_L3_CLKSTCTRL Values */
#define CM_CLKSTCTRL_CLKACTIVITY_EMIF_GCLK BIT_2
#define CM_CLKSTCTRL_CLKACTIVITY_L3_GCLK   BIT_4

/******************** CLOCK MODULE WAKEUP ************************************/
#define CM_WKUP_BASE_ADDR 0x44E00400
#define CM_WKUP_CLKSTCTRL            HWREG32(CM_WKUP_BASE_ADDR + 0x00)
#define CM_WKUP_CONTROL_CLKCTRL      HWREG32(CM_WKUP_BASE_ADDR + 0x04)
#define CM_WKUP_GPIO0_CLKCTRL        HWREG32(CM_WKUP_BASE_ADDR + 0x08)
#define CM_WKUP_L4WKUP_CLKCTRL       HWREG32(CM_WKUP_BASE_ADDR + 0x0C)
#define CM_WKUP_TIMER0_CLKCTRL       HWREG32(CM_WKUP_BASE_ADDR + 0x10)
#define CM_WKUP_DEBUGSS_CLKCTRL      HWREG32(CM_WKUP_BASE_ADDR + 0x14)
#define CM_L3_AON_CLKSTCTRL          HWREG32(CM_WKUP_BASE_ADDR + 0x18)
#define CM_AUTOIDLE_DPLL_MPU         HWREG32(CM_WKUP_BASE_ADDR + 0x1C)
#define CM_IDLEST_DPLL_MPU           HWREG32(CM_WKUP_BASE_ADDR + 0x20)
#define CM_SSC_DELTAMSTEP_DPLL_MPU   HWREG32(CM_WKUP_BASE_ADDR + 0x24)
#define CM_SSC_MODFREQDIV_DPLL_      HWREG32(CM_WKUP_BASE_ADDR + 0x28)
#define CM_CLKSEL_DPLL_MPU           HWREG32(CM_WKUP_BASE_ADDR + 0x2C)
#define CM_AUTOIDLE_DPLL_DDR         HWREG32(CM_WKUP_BASE_ADDR + 0x30)
#define CM_IDLEST_DPLL_DDR           HWREG32(CM_WKUP_BASE_ADDR + 0x34)
#define CM_SSC_DELTAMSTEP_DPLL_DDR   HWREG32(CM_WKUP_BASE_ADDR + 0x38)
#define CM_SSC_MODFREQDIV_DPLL_DDR   HWREG32(CM_WKUP_BASE_ADDR + 0x3C)
#define CM_CLKSEL_DPLL_DDR           HWREG32(CM_WKUP_BASE_ADDR + 0x40)
#define CM_AUTOIDLE_DPLL_DISP        HWREG32(CM_WKUP_BASE_ADDR + 0x44)
#define CM_IDLEST_DPLL_DISP          HWREG32(CM_WKUP_BASE_ADDR + 0x48)
#define CM_SSC_DELTAMSTEP_DPLL_DISP  HWREG32(CM_WKUP_BASE_ADDR + 0x4C)
#define CM_SSC_MODFREQDIV_DPLL_DISP  HWREG32(CM_WKUP_BASE_ADDR + 0x50)
#define CM_CLKSEL_DPLL_DISP          HWREG32(CM_WKUP_BASE_ADDR + 0x54)
#define CM_AUTOIDLE_DPLL_CORE        HWREG32(CM_WKUP_BASE_ADDR + 0x58)
#define CM_IDLEST_DPLL_CORE          HWREG32(CM_WKUP_BASE_ADDR + 0x5C)
#define CM_SSC_DELTAMSTEP_DPLL_CORE  HWREG32(CM_WKUP_BASE_ADDR + 0x60)
#define CM_SSC_MODFREQDIV_DPLL_CORE  HWREG32(CM_WKUP_BASE_ADDR + 0x64)
#define CM_CLKSEL_DPLL_CORE          HWREG32(CM_WKUP_BASE_ADDR + 0x68)
#define CM_AUTOIDLE_DPLL_PER         HWREG32(CM_WKUP_BASE_ADDR + 0x6C)
#define CM_IDLEST_DPLL_PER           HWREG32(CM_WKUP_BASE_ADDR + 0x70)
#define CM_SSC_DELTAMSTEP_DPLL_PER   HWREG32(CM_WKUP_BASE_ADDR + 0x74)
#define CM_SSC_MODFREQDIV_DPLL_PER   HWREG32(CM_WKUP_BASE_ADDR + 0x78)
#define CM_CLKDCOLDO_DPLL_PER        HWREG32(CM_WKUP_BASE_ADDR + 0x7C)
#define CM_DIV_M4_DPLL_CORE          HWREG32(CM_WKUP_BASE_ADDR + 0x80)
#define CM_DIV_M5_DPLL_CORE          HWREG32(CM_WKUP_BASE_ADDR + 0x84)
#define CM_CLKMODE_DPLL_MPU          HWREG32(CM_WKUP_BASE_ADDR + 0x88)
#define CM_CLKMODE_DPLL_PER          HWREG32(CM_WKUP_BASE_ADDR + 0x8C)
#define CM_CLKMODE_DPLL_CORE         HWREG32(CM_WKUP_BASE_ADDR + 0x90)
#define CM_CLKMODE_DPLL_DDR          HWREG32(CM_WKUP_BASE_ADDR + 0x94)
#define CM_CLKMODE_DPLL_DISP         HWREG32(CM_WKUP_BASE_ADDR + 0x98)
#define CM_CLKSEL_DPLL_PERIPH        HWREG32(CM_WKUP_BASE_ADDR + 0x9C)
#define CM_DIV_M2_DPLL_DDR           HWREG32(CM_WKUP_BASE_ADDR + 0xA0)
#define CM_DIV_M2_DPLL_DISP          HWREG32(CM_WKUP_BASE_ADDR + 0xA4)
#define CM_DIV_M2_DPLL_MPU           HWREG32(CM_WKUP_BASE_ADDR + 0xA8)
#define CM_DIV_M2_DPLL_PER           HWREG32(CM_WKUP_BASE_ADDR + 0xAC)
#define CM_WKUP_WKUP_M3_CLKCTRL      HWREG32(CM_WKUP_BASE_ADDR + 0xB0)
#define CM_WKUP_UART0_CLKCTRL        HWREG32(CM_WKUP_BASE_ADDR + 0xB4)
#define CM_WKUP_I2C0_CLKCTRL         HWREG32(CM_WKUP_BASE_ADDR + 0xB8)
#define CM_WKUP_ADC_TSC_CLKCTRL      HWREG32(CM_WKUP_BASE_ADDR + 0xBC)
#define CM_WKUP_SMARTREFLEX0_CLKCTRL HWREG32(CM_WKUP_BASE_ADDR + 0xC0)
#define CM_WKUP_TIMER1_CLKCTRL       HWREG32(CM_WKUP_BASE_ADDR + 0xC4)
#define CM_WKUP_SMARTREFLEX1_CLKCTRL HWREG32(CM_WKUP_BASE_ADDR + 0xC8)
#define CM_L4_WKUP_AON_CLKSTCTRL     HWREG32(CM_WKUP_BASE_ADDR + 0xCC)
#define CM_WKUP_WDT1_CLKCTRL         HWREG32(CM_WKUP_BASE_ADDR + 0xD4)
#define CM_DIV_M6_DPLL_CORE          HWREG32(CM_WKUP_BASE_ADDR + 0xD8)

/* Common to Clock Module */
#define CM_CLKTRCTRL_NO_SLEEP 0x0
#define CM_CLKTRCTRL_SW_SLEEP 0x1
#define CM_CLKTRCTRL_SW_WKUP  0x2

#define CM_MODULE_IDLEST_MASK (BIT_16 | BIT_17)
#define CM_MODULE_IDLEST_FUNC(addr) \
    while (((addr) & CM_MODULE_IDLEST_MASK) != 0x00000) { }
#define CM_MODULE_IDLEST_IDLE(addr) \
    while (((addr) & CM_MODULE_IDLEST_MASK) != 0x20000) { }
#define CM_MODULE_IDLEST_DSBL(addr) \
    while (((addr) & CM_MODULE_IDLEST_MASK) != 0x30000) { }

#define CM_MODULEMODE_MASK (BIT_1 | BIT_0)
#define CM_MODULEMODE_DISABLE(addr) {                 \
    addr &= ~(CM_MODULEMODE_MASK);                    \
    while (((addr) & CM_MODULEMODE_MASK) != 0x0) { }  \
}
#define CM_MODULEMODE_ENABLE(addr) {                  \
    addr |= 0x2;                                      \
    while (((addr) & CM_MODULEMODE_MASK) != 0x2) { }  \
}

/* CM_CLKMODE_DPLL_xxx Values */
#define CM_DPLL_EN_MASK 0x7
#define CM_DPLL_EN_SHFT 0
#define CM_DPLL_EN_MN_BYP_MODE 0x4
#define CM_DPLL_EN_LP_BYP_MODE 0x5
#define CM_DPLL_EN_FR_BYP_MODE 0x6
#define CM_DPLL_EN_LOCK_MODE   0x7

/* CM_IDLEST_DPLL_xxx Values */
#define CM_DPLL_ST_MN_BYPASS BIT_8
#define CM_DPLL_ST_DPLL_CLK  BIT_0

/* CM_CLKSEL_DPLL_xxx Values */
#define CM_DPLL_MULT_MASK 0x7FF00
#define CM_DPLL_MULT_SHFT 8

#define CM_DPLL_DIV_MASK  0x7F
#define CM_DPLL_DIV_SHFT  0

/* CM_DIV_M2_DPLL_xxx Values */
#define CM_DPLL_M2_CLKOUT_DIV_MASK  0x1F
#define CM_DPLL_M2_CLKOUT_DIV_SHFT  0

/* CM_DIV_Mn_DPLL_CORE Values */
#define CM_DPLL_HSDIVIDER_DIV_MASK 0x1F
#define CM_DPLL_HSDIVIDER_DIV_SHFT 0


/******************** CONTROL MODULE *****************************************/
#define CTRLM_BASE_ADDR 0x44E10000

#define CTRLM_CONTROL_REVISION          HWREG32(CTRLM_BASE_ADDR + 0x000)
#define CTRLM_CONTROL_HWINFO            HWREG32(CTRLM_BASE_ADDR + 0x004)
#define CTRLM_CONTROL_SYSCONFIG         HWREG32(CTRLM_BASE_ADDR + 0x010)
#define CTRLM_CONTROL_STATUS            HWREG32(CTRLM_BASE_ADDR + 0x040)
#define CTRLM_CONTROL_EMIF_SDRAM_CONFIG HWREG32(CTRLM_BASE_ADDR + 0x110)
#define CTRLM_CORTEX_VBBLDO_CTRL        HWREG32(CTRLM_BASE_ADDR + 0x41C)
#define CTRLM_CORE_SLDO_CTRL            HWREG32(CTRLM_BASE_ADDR + 0x428)
#define CTRLM_MPU_SLDO_CTRL             HWREG32(CTRLM_BASE_ADDR + 0x42C)
#define CTRLM_CLK32KDIVRATIO_CTRL       HWREG32(CTRLM_BASE_ADDR + 0x444)
#define CTRLM_BANDGAP_CTRL              HWREG32(CTRLM_BASE_ADDR + 0x448)
#define CTRLM_BANDGAP_TRIM              HWREG32(CTRLM_BASE_ADDR + 0x44C)
#define CTRLM_PLL_CLKINPULOW_CTRL       HWREG32(CTRLM_BASE_ADDR + 0x458)
#define CTRLM_MOSC_CTRL                 HWREG32(CTRLM_BASE_ADDR + 0x468)
#define CTRLM_RCOSC_CTRL                HWREG32(CTRLM_BASE_ADDR + 0x46C)
#define CTRLM_DEEPSLEEP_CTRL            HWREG32(CTRLM_BASE_ADDR + 0x470)
#define CTRLM_DEVICE_ID                 HWREG32(CTRLM_BASE_ADDR + 0x600)
#define CTRLM_DEV_FEATURE               HWREG32(CTRLM_BASE_ADDR + 0x604)
#define CTRLM_INIT_PRIORITY_0           HWREG32(CTRLM_BASE_ADDR + 0x608)
#define CTRLM_INIT_PRIORITY_1           HWREG32(CTRLM_BASE_ADDR + 0x60C)
#define CTRLM_MMU_CFG                   HWREG32(CTRLM_BASE_ADDR + 0x610)
#define CTRLM_TPTC_CFG                  HWREG32(CTRLM_BASE_ADDR + 0x614)
#define CTRLM_USB_CTRL0                 HWREG32(CTRLM_BASE_ADDR + 0x620)
#define CTRLM_USB_STS0                  HWREG32(CTRLM_BASE_ADDR + 0x624)
#define CTRLM_USB_CTRL1                 HWREG32(CTRLM_BASE_ADDR + 0x628)
#define CTRLM_USB_STS1                  HWREG32(CTRLM_BASE_ADDR + 0x62C)
#define CTRLM_MAC_ID0_LO                HWREG32(CTRLM_BASE_ADDR + 0x630)
#define CTRLM_MAC_ID0_HI                HWREG32(CTRLM_BASE_ADDR + 0x634)
#define CTRLM_MAC_ID1_LO                HWREG32(CTRLM_BASE_ADDR + 0x638)
#define CTRLM_MAC_ID1_HI                HWREG32(CTRLM_BASE_ADDR + 0x63C)
#define CTRLM_DCAN_RAMINIT              HWREG32(CTRLM_BASE_ADDR + 0x644)
#define CTRLM_USB_WKUP_CTRL             HWREG32(CTRLM_BASE_ADDR + 0x648)
#define CTRLM_GMII_SEL                  HWREG32(CTRLM_BASE_ADDR + 0x650)
#define CTRLM_PWMSS_CTRL                HWREG32(CTRLM_BASE_ADDR + 0x664)
#define CTRLM_MREQPRIO_0                HWREG32(CTRLM_BASE_ADDR + 0x670)
#define CTRLM_MREQPRIO_1                HWREG32(CTRLM_BASE_ADDR + 0x674)
#define CTRLM_HW_EVENT_SEL_GRP1         HWREG32(CTRLM_BASE_ADDR + 0x690)
#define CTRLM_HW_EVENT_SEL_GRP2         HWREG32(CTRLM_BASE_ADDR + 0x694)
#define CTRLM_HW_EVENT_SEL_GRP3         HWREG32(CTRLM_BASE_ADDR + 0x698)
#define CTRLM_HW_EVENT_SEL_GRP4         HWREG32(CTRLM_BASE_ADDR + 0x69C)
#define CTRLM_SMRT_CTRL                 HWREG32(CTRLM_BASE_ADDR + 0x6A0)
#define CTRLM_MPUSS_HW_DEBUG_SEL        HWREG32(CTRLM_BASE_ADDR + 0x6A4)
#define CTRLM_MPUSS_HW_DBG_INFO         HWREG32(CTRLM_BASE_ADDR + 0x6A8)
#define CTRLM_VDD_MPU_OPP_050           HWREG32(CTRLM_BASE_ADDR + 0x770)
#define CTRLM_VDD_MPU_OPP_100           HWREG32(CTRLM_BASE_ADDR + 0x774)
#define CTRLM_VDD_MPU_OPP_120           HWREG32(CTRLM_BASE_ADDR + 0x778)
#define CTRLM_VDD_MPU_OPP_TURBO         HWREG32(CTRLM_BASE_ADDR + 0x77C)
#define CTRLM_VDD_CORE_OPP_050          HWREG32(CTRLM_BASE_ADDR + 0x7B8)
#define CTRLM_VDD_CORE_OPP_100          HWREG32(CTRLM_BASE_ADDR + 0x7BC)
#define CTRLM_BB_SCALE                  HWREG32(CTRLM_BASE_ADDR + 0x7D0)
#define CTRLM_USB_VID_PID               HWREG32(CTRLM_BASE_ADDR + 0x7F4)
#define CTRLM_CONF_GPMC_AD(n)  HWREG32(CTRLM_BASE_ADDR + 0x800 + ((n)*4))
#define CTRLM_CONF_GPMC_A(n)   HWREG32(CTRLM_BASE_ADDR + 0x840 + ((n)*4))
#define CTRLM_CONF_GPMC_WAIT0           HWREG32(CTRLM_BASE_ADDR + 0x870)
#define CTRLM_CONF_GPMC_WPN             HWREG32(CTRLM_BASE_ADDR + 0x874)
#define CTRLM_CONF_GPMC_BEN1            HWREG32(CTRLM_BASE_ADDR + 0x878)
#define CTRLM_CONF_GPMC_CSN0            HWREG32(CTRLM_BASE_ADDR + 0x87C)
#define CTRLM_CONF_GPMC_CSN1            HWREG32(CTRLM_BASE_ADDR + 0x880)
#define CTRLM_CONF_GPMC_CSN2            HWREG32(CTRLM_BASE_ADDR + 0x884)
#define CTRLM_CONF_GPMC_CSN3            HWREG32(CTRLM_BASE_ADDR + 0x888)
#define CTRLM_CONF_GPMC_CLK             HWREG32(CTRLM_BASE_ADDR + 0x88C)
#define CTRLM_CONF_GPMC_ADVN_ALE        HWREG32(CTRLM_BASE_ADDR + 0x890)
#define CTRLM_CONF_GPMC_OEN_REN         HWREG32(CTRLM_BASE_ADDR + 0x894)
#define CTRLM_CONF_GPMC_WEN             HWREG32(CTRLM_BASE_ADDR + 0x898)
#define CTRLM_CONF_GPMC_BEN0_CLE        HWREG32(CTRLM_BASE_ADDR + 0x89C)
#define CTRLM_CONF_LCD_DATA(n) HWREG32(CTRLM_BASE_ADDR + 0x8A0 + ((n)*4))
#define CTRLM_CONF_LCD_VSYNC            HWREG32(CTRLM_BASE_ADDR + 0x8E0)
#define CTRLM_CONF_LCD_HSYNC            HWREG32(CTRLM_BASE_ADDR + 0x8E4)
#define CTRLM_CONF_LCD_PCLK             HWREG32(CTRLM_BASE_ADDR + 0x8E8)
#define CTRLM_CONF_LCD_AC_BIAS_EN       HWREG32(CTRLM_BASE_ADDR + 0x8EC)
#define CTRLM_CONF_MMC0_DAT3            HWREG32(CTRLM_BASE_ADDR + 0x8F0)
#define CTRLM_CONF_MMC0_DAT2            HWREG32(CTRLM_BASE_ADDR + 0x8F4)
#define CTRLM_CONF_MMC0_DAT1            HWREG32(CTRLM_BASE_ADDR + 0x8F8)
#define CTRLM_CONF_MMC0_DAT0            HWREG32(CTRLM_BASE_ADDR + 0x8FC)
#define CTRLM_CONF_MMC0_CLK             HWREG32(CTRLM_BASE_ADDR + 0x900)
#define CTRLM_CONF_MMC0_CMD             HWREG32(CTRLM_BASE_ADDR + 0x904)
#define CTRLM_CONF_MII1_COL             HWREG32(CTRLM_BASE_ADDR + 0x908)
#define CTRLM_CONF_MII1_CRS             HWREG32(CTRLM_BASE_ADDR + 0x90C)
#define CTRLM_CONF_MII1_RX_ER           HWREG32(CTRLM_BASE_ADDR + 0x910)
#define CTRLM_CONF_MII1_TX_EN           HWREG32(CTRLM_BASE_ADDR + 0x914)
#define CTRLM_CONF_MII1_RX_DV           HWREG32(CTRLM_BASE_ADDR + 0x918)
#define CTRLM_CONF_MII1_TXD3            HWREG32(CTRLM_BASE_ADDR + 0x91C)
#define CTRLM_CONF_MII1_TXD2            HWREG32(CTRLM_BASE_ADDR + 0x920)
#define CTRLM_CONF_MII1_TXD1            HWREG32(CTRLM_BASE_ADDR + 0x924)
#define CTRLM_CONF_MII1_TXD0            HWREG32(CTRLM_BASE_ADDR + 0x928)
#define CTRLM_CONF_MII1_TX_CLK          HWREG32(CTRLM_BASE_ADDR + 0x92C)
#define CTRLM_CONF_MII1_RX_CLK          HWREG32(CTRLM_BASE_ADDR + 0x930)
#define CTRLM_CONF_MII1_RXD3            HWREG32(CTRLM_BASE_ADDR + 0x934)
#define CTRLM_CONF_MII1_RXD2            HWREG32(CTRLM_BASE_ADDR + 0x938)
#define CTRLM_CONF_MII1_RXD1            HWREG32(CTRLM_BASE_ADDR + 0x93C)
#define CTRLM_CONF_MII1_RXD0            HWREG32(CTRLM_BASE_ADDR + 0x940)
#define CTRLM_CONF_RMII1_REF_CLK        HWREG32(CTRLM_BASE_ADDR + 0x944)
#define CTRLM_CONF_MDIO                 HWREG32(CTRLM_BASE_ADDR + 0x948)
#define CTRLM_CONF_MDC                  HWREG32(CTRLM_BASE_ADDR + 0x94C)
#define CTRLM_CONF_SPI0_SCLK            HWREG32(CTRLM_BASE_ADDR + 0x950)
#define CTRLM_CONF_SPI0_D0              HWREG32(CTRLM_BASE_ADDR + 0x954)
#define CTRLM_CONF_SPI0_D1              HWREG32(CTRLM_BASE_ADDR + 0x958)
#define CTRLM_CONF_SPI0_CS0             HWREG32(CTRLM_BASE_ADDR + 0x95C)
#define CTRLM_CONF_SPI0_CS1             HWREG32(CTRLM_BASE_ADDR + 0x960)
#define CTRLM_CONF_ECAP0_IN_PWM0_OUT    HWREG32(CTRLM_BASE_ADDR + 0x964)
#define CTRLM_CONF_UART0_CTSN           HWREG32(CTRLM_BASE_ADDR + 0x968)
#define CTRLM_CONF_UART0_RTSN           HWREG32(CTRLM_BASE_ADDR + 0x96C)
#define CTRLM_CONF_UART0_RXD            HWREG32(CTRLM_BASE_ADDR + 0x970)
#define CTRLM_CONF_UART0_TXD            HWREG32(CTRLM_BASE_ADDR + 0x974)
#define CTRLM_CONF_UART1_CTSN           HWREG32(CTRLM_BASE_ADDR + 0x978)
#define CTRLM_CONF_UART1_RTSN           HWREG32(CTRLM_BASE_ADDR + 0x97C)
#define CTRLM_CONF_UART1_RXD            HWREG32(CTRLM_BASE_ADDR + 0x980)
#define CTRLM_CONF_UART1_TXD            HWREG32(CTRLM_BASE_ADDR + 0x984)
#define CTRLM_CONF_I2C0_SDA             HWREG32(CTRLM_BASE_ADDR + 0x988)
#define CTRLM_CONF_I2C0_SCL             HWREG32(CTRLM_BASE_ADDR + 0x98C)
#define CTRLM_CONF_MCASP0_ACLKX         HWREG32(CTRLM_BASE_ADDR + 0x990)
#define CTRLM_CONF_MCASP0_FSX           HWREG32(CTRLM_BASE_ADDR + 0x994)
#define CTRLM_CONF_MCASP0_AXR0          HWREG32(CTRLM_BASE_ADDR + 0x998)
#define CTRLM_CONF_MCASP0_AHCLKR        HWREG32(CTRLM_BASE_ADDR + 0x99C)
#define CTRLM_CONF_MCASP0_ACLKR         HWREG32(CTRLM_BASE_ADDR + 0x9A0)
#define CTRLM_CONF_MCASP0_FSR           HWREG32(CTRLM_BASE_ADDR + 0x9A4)
#define CTRLM_CONF_MCASP0_AXR1          HWREG32(CTRLM_BASE_ADDR + 0x9A8)
#define CTRLM_CONF_MCASP0_AHCLKX        HWREG32(CTRLM_BASE_ADDR + 0x9AC)
#define CTRLM_CONF_XDMA_EVENT_INTR0     HWREG32(CTRLM_BASE_ADDR + 0x9B0)
#define CTRLM_CONF_XDMA_EVENT_INTR1     HWREG32(CTRLM_BASE_ADDR + 0x9B4)
#define CTRLM_CONF_WARMRSTN             HWREG32(CTRLM_BASE_ADDR + 0x9B8)
#define CTRLM_CONF_PWRONRSTN            HWREG32(CTRLM_BASE_ADDR + 0x9BC)
#define CTRLM_CONF_NNMI                 HWREG32(CTRLM_BASE_ADDR + 0x9C0)
#define CTRLM_CONF_XTALIN               HWREG32(CTRLM_BASE_ADDR + 0x9C4)
#define CTRLM_CONF_XTALOUT              HWREG32(CTRLM_BASE_ADDR + 0x9C8)
#define CTRLM_CONF_TMS                  HWREG32(CTRLM_BASE_ADDR + 0x9D0)
#define CTRLM_CONF_TDI                  HWREG32(CTRLM_BASE_ADDR + 0x9D4)
#define CTRLM_CONF_TDO                  HWREG32(CTRLM_BASE_ADDR + 0x9D8)
#define CTRLM_CONF_TCK                  HWREG32(CTRLM_BASE_ADDR + 0x9DC)
#define CTRLM_CONF_TRSTN                HWREG32(CTRLM_BASE_ADDR + 0x9E0)
#define CTRLM_CONF_EMU0                 HWREG32(CTRLM_BASE_ADDR + 0x9E4)
#define CTRLM_CONF_EMU1                 HWREG32(CTRLM_BASE_ADDR + 0x9E8)
#define CTRLM_CONF_RTC_XTALIN           HWREG32(CTRLM_BASE_ADDR + 0x9EC)
#define CTRLM_CONF_RTC_XTALOUT          HWREG32(CTRLM_BASE_ADDR + 0x9F0)
#define CTRLM_CONF_RTC_PWRONRSTN        HWREG32(CTRLM_BASE_ADDR + 0x9F8)
#define CTRLM_CONF_PMIC_POWER_EN        HWREG32(CTRLM_BASE_ADDR + 0x9FC)
#define CTRLM_CONF_EXT_WAKEUP           HWREG32(CTRLM_BASE_ADDR + 0xA00)
#define CTRLM_CONF_RTC_KALDO_ENN        HWREG32(CTRLM_BASE_ADDR + 0xA04)
#define CTRLM_CONF_USB0_DM              HWREG32(CTRLM_BASE_ADDR + 0xA08)
#define CTRLM_CONF_USB0_DP              HWREG32(CTRLM_BASE_ADDR + 0xA0C)
#define CTRLM_CONF_USB0_CE              HWREG32(CTRLM_BASE_ADDR + 0xA10)
#define CTRLM_CONF_USB0_ID              HWREG32(CTRLM_BASE_ADDR + 0xA14)
#define CTRLM_CONF_USB0_VBUS            HWREG32(CTRLM_BASE_ADDR + 0xA18)
#define CTRLM_CONF_USB0_DRVVBUS         HWREG32(CTRLM_BASE_ADDR + 0xA1C)
#define CTRLM_CONF_USB1_DM              HWREG32(CTRLM_BASE_ADDR + 0xA20)
#define CTRLM_CONF_USB1_DP              HWREG32(CTRLM_BASE_ADDR + 0xA24)
#define CTRLM_CONF_USB1_CE              HWREG32(CTRLM_BASE_ADDR + 0xA28)
#define CTRLM_CONF_USB1_ID              HWREG32(CTRLM_BASE_ADDR + 0xA2C)
#define CTRLM_CONF_USB1_VBUS            HWREG32(CTRLM_BASE_ADDR + 0xA30)
#define CTRLM_CONF_USB1_DRVVBUS         HWREG32(CTRLM_BASE_ADDR + 0xA34)
#define CTRLM_CQDETECT_STATUS           HWREG32(CTRLM_BASE_ADDR + 0xE00)
#define CTRLM_DDR_IO_CTRL               HWREG32(CTRLM_BASE_ADDR + 0xE04)
#define CTRLM_VTP_CTRL                  HWREG32(CTRLM_BASE_ADDR + 0xE0C)
#define CTRLM_VREF_CTRL                 HWREG32(CTRLM_BASE_ADDR + 0xE14)
#define CTRLM_TPCC_EVT_MUX_0_3          HWREG32(CTRLM_BASE_ADDR + 0xF90)
#define CTRLM_TPCC_EVT_MUX_4_7          HWREG32(CTRLM_BASE_ADDR + 0xF94)
#define CTRLM_TPCC_EVT_MUX_8_11         HWREG32(CTRLM_BASE_ADDR + 0xF98)
#define CTRLM_TPCC_EVT_MUX_12_15        HWREG32(CTRLM_BASE_ADDR + 0xF9C)
#define CTRLM_TPCC_EVT_MUX_16_19        HWREG32(CTRLM_BASE_ADDR + 0xFA0)
#define CTRLM_TPCC_EVT_MUX_20_23        HWREG32(CTRLM_BASE_ADDR + 0xFA4)
#define CTRLM_TPCC_EVT_MUX_24_27        HWREG32(CTRLM_BASE_ADDR + 0xFA8)
#define CTRLM_TPCC_EVT_MUX_28_31        HWREG32(CTRLM_BASE_ADDR + 0xFAC)
#define CTRLM_TPCC_EVT_MUX_32_35        HWREG32(CTRLM_BASE_ADDR + 0xFB0)
#define CTRLM_TPCC_EVT_MUX_36_39        HWREG32(CTRLM_BASE_ADDR + 0xFB4)
#define CTRLM_TPCC_EVT_MUX_40_43        HWREG32(CTRLM_BASE_ADDR + 0xFB8)
#define CTRLM_TPCC_EVT_MUX_44_47        HWREG32(CTRLM_BASE_ADDR + 0xFBC)
#define CTRLM_TPCC_EVT_MUX_48_51        HWREG32(CTRLM_BASE_ADDR + 0xFC0)
#define CTRLM_TPCC_EVT_MUX_52_55        HWREG32(CTRLM_BASE_ADDR + 0xFC4)
#define CTRLM_TPCC_EVT_MUX_56_59        HWREG32(CTRLM_BASE_ADDR + 0xFC8)
#define CTRLM_TPCC_EVT_MUX_60_63        HWREG32(CTRLM_BASE_ADDR + 0xFCC)
#define CTRLM_TIMER_EVT_CAPT            HWREG32(CTRLM_BASE_ADDR + 0xFD0)
#define CTRLM_ECAP_EVT_CAPT             HWREG32(CTRLM_BASE_ADDR + 0xFD4)
#define CTRLM_ADC_EVT_CAPT              HWREG32(CTRLM_BASE_ADDR + 0xFD8)
#define CTRLM_RESET_ISO                 HWREG32(CTRLM_BASE_ADDR + 0x1000)
#define CTRLM_DDR_CKE_CTRL              HWREG32(CTRLM_BASE_ADDR + 0x131C)
#define CTRLM_SMA2                      HWREG32(CTRLM_BASE_ADDR + 0x1320)
#define CTRLM_M3_TXEV_EOI               HWREG32(CTRLM_BASE_ADDR + 0x1324)
#define CTRLM_IPC_MSG_REG(n)    HWREG32(CTRLM_BASE_ADDR + 0x1328 + ((n)*4))
#define CTRLM_DDR_CMD0_IOCTRL           HWREG32(CTRLM_BASE_ADDR + 0x1404)
#define CTRLM_DDR_CMD1_IOCTRL           HWREG32(CTRLM_BASE_ADDR + 0x1408)
#define CTRLM_DDR_CMD2_IOCTRL           HWREG32(CTRLM_BASE_ADDR + 0x140C)
#define CTRLM_DDR_DATA0_IOCTRL          HWREG32(CTRLM_BASE_ADDR + 0x1440)
#define CTRLM_DDR_DATA1_IOCTRL          HWREG32(CTRLM_BASE_ADDR + 0x1444)

#define CTRLM_CONF_SLEWCTRL   BIT_6
#define CTRLM_CONF_RXACTIVE   BIT_5
#define CTRLM_CONF_PUTYPESEL  BIT_4
#define CTRLM_CONF_PUDEN      BIT_3
#define CTRLM_CONF_MUXMODE(n) ((n) & 0x7)

#define CTRLM_VTP_CTRL_CLRZ   BIT_0
#define CTRLM_VTP_CTRL_READY  BIT_5
#define CTRLM_VTP_CTRL_ENABLE BIT_6

/*********************** EMIF MODULE *****************************************/
#define EMIF_BASE_ADDR 0x4C000000

#define EMIF_MOD_ID_REV             HWREG32(EMIF_BASE_ADDR + 0x000)
#define EMIF_STATUS                 HWREG32(EMIF_BASE_ADDR + 0x004)
#define EMIF_SDRAM_CONFIG           HWREG32(EMIF_BASE_ADDR + 0x008)
#define EMIF_SDRAM_CONFIG_2         HWREG32(EMIF_BASE_ADDR + 0x00C)
#define EMIF_SDRAM_REF_CTRL         HWREG32(EMIF_BASE_ADDR + 0x010)
#define EMIF_SDRAM_REF_CTRL_SHDW    HWREG32(EMIF_BASE_ADDR + 0x014)
#define EMIF_SDRAM_TIM_1            HWREG32(EMIF_BASE_ADDR + 0x018)
#define EMIF_SDRAM_TIM_1_SHDW       HWREG32(EMIF_BASE_ADDR + 0x01C)
#define EMIF_SDRAM_TIM_2            HWREG32(EMIF_BASE_ADDR + 0x020)
#define EMIF_SDRAM_TIM_2_SHDW       HWREG32(EMIF_BASE_ADDR + 0x024)
#define EMIF_SDRAM_TIM_3            HWREG32(EMIF_BASE_ADDR + 0x028)
#define EMIF_SDRAM_TIM_3_SHDW       HWREG32(EMIF_BASE_ADDR + 0x02C)
#define EMIF_PWR_MGMT_CTRL          HWREG32(EMIF_BASE_ADDR + 0x038)
#define EMIF_PWR_MGMT_CTRL_SHDW     HWREG32(EMIF_BASE_ADDR + 0x03C)
#define EMIF_INT_CONFIG             HWREG32(EMIF_BASE_ADDR + 0x054)
#define EMIF_INT_CFG_VAL_1          HWREG32(EMIF_BASE_ADDR + 0x058)
#define EMIF_INT_CFG_VAL_2          HWREG32(EMIF_BASE_ADDR + 0x05C)
#define EMIF_PERF_CNT_1             HWREG32(EMIF_BASE_ADDR + 0x080)
#define EMIF_PERF_CNT_2             HWREG32(EMIF_BASE_ADDR + 0x084)
#define EMIF_PERF_CNT_CFG           HWREG32(EMIF_BASE_ADDR + 0x088)
#define EMIF_PERF_CNT_SEL           HWREG32(EMIF_BASE_ADDR + 0x08C)
#define EMIF_PERF_CNT_TIM           HWREG32(EMIF_BASE_ADDR + 0x090)
#define EMIF_READ_IDLE_CTRL         HWREG32(EMIF_BASE_ADDR + 0x098)
#define EMIF_READ_IDLE_CTRL_SHDW    HWREG32(EMIF_BASE_ADDR + 0x09C)
#define EMIF_IRQSTATUS_RAW_SYS      HWREG32(EMIF_BASE_ADDR + 0x0A4)
#define EMIF_IRQSTATUS_SYS          HWREG32(EMIF_BASE_ADDR + 0x0AC)
#define EMIF_IRQENABLE_SET_SYS      HWREG32(EMIF_BASE_ADDR + 0x0B4)
#define EMIF_IRQENABLE_CLR_SYS      HWREG32(EMIF_BASE_ADDR + 0x0BC)
#define EMIF_ZQ_CONFIG              HWREG32(EMIF_BASE_ADDR + 0x0C8)
#define EMIF_RDWR_LVL_RMP_WIN       HWREG32(EMIF_BASE_ADDR + 0x0D4)
#define EMIF_RDWR_LVL_RMP_CTRL      HWREG32(EMIF_BASE_ADDR + 0x0D8)
#define EMIF_RDWR_LVL_CTRL          HWREG32(EMIF_BASE_ADDR + 0x0DC)
#define EMIF_DDR_PHY_CTRL_1         HWREG32(EMIF_BASE_ADDR + 0x0E4)
#define EMIF_DDR_PHY_CTRL_1_SHDW    HWREG32(EMIF_BASE_ADDR + 0x0E8)
#define EMIF_DDR_PHY_CTRL_2         HWREG32(EMIF_BASE_ADDR + 0x0EC)
#define EMIF_PRI_COS_MAP            HWREG32(EMIF_BASE_ADDR + 0x100)
#define EMIF_CONNID_COS_1_MAP       HWREG32(EMIF_BASE_ADDR + 0x104)
#define EMIF_CONNID_COS_2_MAP       HWREG32(EMIF_BASE_ADDR + 0x108)
#define EMIF_RD_WR_EXEC_THRSH       HWREG32(EMIF_BASE_ADDR + 0x120)

/*********************** DDR_PHY MODULE ***************************************/
#define DDRPHY_BASE_ADDR 0x44E12000

#define DDRPHY_CMD0_SLAVE_RATIO_0           HWREG32(DDRPHY_BASE_ADDR + 0x1C)
#define DDRPHY_CMD0_SLAVE_FORCE_0           HWREG32(DDRPHY_BASE_ADDR + 0x20)
#define DDRPHY_CMD0_SLAVE_DELAY_0           HWREG32(DDRPHY_BASE_ADDR + 0x24)
#define DDRPHY_CMD0_LOCK_DIFF_0             HWREG32(DDRPHY_BASE_ADDR + 0x28)
#define DDRPHY_CMD0_INVERT_CLKOUT_0         HWREG32(DDRPHY_BASE_ADDR + 0x2C)
#define DDRPHY_CMD1_SLAVE_RATIO_0           HWREG32(DDRPHY_BASE_ADDR + 0x50)
#define DDRPHY_CMD1_SLAVE_FORCE_0           HWREG32(DDRPHY_BASE_ADDR + 0x54)
#define DDRPHY_CMD1_SLAVE_DELAY_0           HWREG32(DDRPHY_BASE_ADDR + 0x58)
#define DDRPHY_CMD1_LOCK_DIFF_0             HWREG32(DDRPHY_BASE_ADDR + 0x5C)
#define DDRPHY_CMD1_INVERT_CLKOUT_0         HWREG32(DDRPHY_BASE_ADDR + 0x60)
#define DDRPHY_CMD2_SLAVE_RATIO_0           HWREG32(DDRPHY_BASE_ADDR + 0x84)
#define DDRPHY_CMD2_SLAVE_FORCE_0           HWREG32(DDRPHY_BASE_ADDR + 0x88)
#define DDRPHY_CMD2_SLAVE_DELAY_0           HWREG32(DDRPHY_BASE_ADDR + 0x8C)
#define DDRPHY_CMD2_LOCK_DIFF_0             HWREG32(DDRPHY_BASE_ADDR + 0x90)
#define DDRPHY_CMD2_INVERT_CLKOUT_0         HWREG32(DDRPHY_BASE_ADDR + 0x94)
#define DDRPHY_DATA0_RD_DQS_SLAVE_RATIO_0   HWREG32(DDRPHY_BASE_ADDR + 0xC8)
#define DDRPHY_DATA0_RD_DQS_SLAVE_RATIO_1   HWREG32(DDRPHY_BASE_ADDR + 0xCC)
#define DDRPHY_DATA0_WR_DQS_SLAVE_RATIO_0   HWREG32(DDRPHY_BASE_ADDR + 0xDC)
#define DDRPHY_DATA0_WR_DQS_SLAVE_RATIO_1   HWREG32(DDRPHY_BASE_ADDR + 0xE0)
#define DDRPHY_DATA0_WRLVL_INIT_RATIO_0     HWREG32(DDRPHY_BASE_ADDR + 0xF0)
#define DDRPHY_DATA0_WRLVL_INIT_RATIO_1     HWREG32(DDRPHY_BASE_ADDR + 0xF4)
#define DDRPHY_DATA0_GATELVL_INIT_RATIO_0   HWREG32(DDRPHY_BASE_ADDR + 0xFC)
#define DDRPHY_DATA0_GATELVL_INIT_RATIO_1   HWREG32(DDRPHY_BASE_ADDR + 0x100)
#define DDRPHY_DATA0_FIFO_WE_SLAVE_RATIO_0  HWREG32(DDRPHY_BASE_ADDR + 0x108)
#define DDRPHY_DATA0_FIFO_WE_SLAVE_RATIO_1  HWREG32(DDRPHY_BASE_ADDR + 0x10C)
#define DDRPHY_DATA0_WR_DATA_SLAVE_RATIO_0  HWREG32(DDRPHY_BASE_ADDR + 0x120)
#define DDRPHY_DATA0_WR_DATA_SLAVE_RATIO_1  HWREG32(DDRPHY_BASE_ADDR + 0x124)
#define DDRPHY_DATA0_USE_RANK0_DELAYS_0     HWREG32(DDRPHY_BASE_ADDR + 0x134)
#define DDRPHY_DATA0_LOCK_DIFF_0            HWREG32(DDRPHY_BASE_ADDR + 0x138)
#define DDRPHY_DATA1_RD_DQS_SLAVE_RATIO_0   HWREG32(DDRPHY_BASE_ADDR + 0x16c)
#define DDRPHY_DATA1_RD_DQS_SLAVE_RATIO_1   HWREG32(DDRPHY_BASE_ADDR + 0x170)
#define DDRPHY_DATA1_WR_DQS_SLAVE_RATIO_0   HWREG32(DDRPHY_BASE_ADDR + 0x180)
#define DDRPHY_DATA1_WR_DQS_SLAVE_RATIO_1   HWREG32(DDRPHY_BASE_ADDR + 0x184)
#define DDRPHY_DATA1_WRLVL_INIT_RATIO_0     HWREG32(DDRPHY_BASE_ADDR + 0x194)
#define DDRPHY_DATA1_WRLVL_INIT_RATIO_1     HWREG32(DDRPHY_BASE_ADDR + 0x198)
#define DDRPHY_DATA1_GATELVL_INIT_RATIO_0   HWREG32(DDRPHY_BASE_ADDR + 0x1a0)
#define DDRPHY_DATA1_GATELVL_INIT_RATIO_1   HWREG32(DDRPHY_BASE_ADDR + 0x1a4)
#define DDRPHY_DATA1_FIFO_WE_SLAVE_RATIO_0  HWREG32(DDRPHY_BASE_ADDR + 0x1ac)
#define DDRPHY_DATA1_FIFO_WE_SLAVE_RATIO_1  HWREG32(DDRPHY_BASE_ADDR + 0x1b0)
#define DDRPHY_DATA1_WR_DATA_SLAVE_RATIO_0  HWREG32(DDRPHY_BASE_ADDR + 0x1c4)
#define DDRPHY_DATA1_WR_DATA_SLAVE_RATIO_1  HWREG32(DDRPHY_BASE_ADDR + 0x1c8)
#define DDRPHY_DATA1_USE_RANK0_DELAYS_0     HWREG32(DDRPHY_BASE_ADDR + 0x1d8)
#define DDRPHY_DATA1_LOCK_DIFF_0            HWREG32(DDRPHY_BASE_ADDR + 0x1dc)

/*********************** GPIO MODULE *****************************************/
#define GPIO0_BASE_ADDR 0x44E07000
#define GPIO1_BASE_ADDR 0x4804C000
#define GPIO2_BASE_ADDR 0x481AC000
#define GPIO3_BASE_ADDR 0x481AE000

#define GPIO_REVISION(base)         HWREG32((base) + 0x000)
#define GPIO_SYSCONFIG(base)        HWREG32((base) + 0x010)
#define GPIO_IRQSTATUS_RAW_0(base)  HWREG32((base) + 0x024)
#define GPIO_IRQSTATUS_RAW_1(base)  HWREG32((base) + 0x028)
#define GPIO_IRQSTATUS_0(base)      HWREG32((base) + 0x02C)
#define GPIO_IRQSTATUS_1(base)      HWREG32((base) + 0x030)
#define GPIO_IRQSTATUS_SET_0(base)  HWREG32((base) + 0x034)
#define GPIO_IRQSTATUS_SET_1(base)  HWREG32((base) + 0x038)
#define GPIO_IRQSTATUS_CLR_0(base)  HWREG32((base) + 0x03C)
#define GPIO_IRQSTATUS_CLR_1(base)  HWREG32((base) + 0x040)
#define GPIO_IRQWAKEN_0(base)       HWREG32((base) + 0x044)
#define GPIO_IRQWAKEN_1(base)       HWREG32((base) + 0x048)
#define GPIO_SYSSTATUS(base)        HWREG32((base) + 0x114)
#define GPIO_CTRL(base)             HWREG32((base) + 0x130)
#define GPIO_OE(base)               HWREG32((base) + 0x134)
#define GPIO_DATAIN(base)           HWREG32((base) + 0x138)
#define GPIO_DATAOUT(base)          HWREG32((base) + 0x13C)
#define GPIO_LEVELDETECT0(base)     HWREG32((base) + 0x140)
#define GPIO_LEVELDETECT1(base)     HWREG32((base) + 0x144)
#define GPIO_RISINGDETECT(base)     HWREG32((base) + 0x148)
#define GPIO_FALLINGDETECT(base)    HWREG32((base) + 0x14C)
#define GPIO_DEBOUNCENABLE(base)    HWREG32((base) + 0x150)
#define GPIO_DEBOUNCINGTIME(base)   HWREG32((base) + 0x154)
#define GPIO_CLEARDATAOUT(base)     HWREG32((base) + 0x190)
#define GPIO_SETDATAOUT(base)       HWREG32((base) + 0x194)

/*********************** UART MODULE *****************************************/
#define UART0_BASE_ADDR 0x44E09000
#define UART1_BASE_ADDR 0x48022000
#define UART2_BASE_ADDR 0x48024000
#define UART3_BASE_ADDR 0x481A6000
#define UART4_BASE_ADDR 0x481A8000
#define UART5_BASE_ADDR 0x481AA000

#define UART_DLL(base)              HWREG32((base) + 0x00)
#define UART_RHR(base)              HWREG32((base) + 0x00)
#define UART_THR(base)              HWREG32((base) + 0x00)
#define UART_DLH(base)              HWREG32((base) + 0x04)
#define UART_IER(base)              HWREG32((base) + 0x04)
#define UART_EFR(base)              HWREG32((base) + 0x08)
#define UART_FCR(base)              HWREG32((base) + 0x08)
#define UART_IIR(base)              HWREG32((base) + 0x08)
#define UART_LCR(base)              HWREG32((base) + 0x0C)
#define UART_MCR(base)              HWREG32((base) + 0x10)
#define UART_XON1_ADDR1(base)       HWREG32((base) + 0x10)
#define UART_LSR(base)              HWREG32((base) + 0x14)
#define UART_XON2_ADDR2(base)       HWREG32((base) + 0x14)
#define UART_MSR(base)              HWREG32((base) + 0x18)
#define UART_TCR(base)              HWREG32((base) + 0x18)
#define UART_XOFF1(base)            HWREG32((base) + 0x18)
#define UART_SPR(base)              HWREG32((base) + 0x1C)
#define UART_TLR(base)              HWREG32((base) + 0x1C)
#define UART_XOFF2(base)            HWREG32((base) + 0x1C)
#define UART_MDR1(base)             HWREG32((base) + 0x20)
#define UART_MDR2(base)             HWREG32((base) + 0x24)
#define UART_SFLSR(base)            HWREG32((base) + 0x28)
#define UART_TXFLL(base)            HWREG32((base) + 0x28)
#define UART_RESUME(base)           HWREG32((base) + 0x2C)
#define UART_TXFLH(base)            HWREG32((base) + 0x2C)
#define UART_RXFLL(base)            HWREG32((base) + 0x30)
#define UART_SFREGL(base)           HWREG32((base) + 0x30)
#define UART_RXFLH(base)            HWREG32((base) + 0x34)
#define UART_SFREGH(base)           HWREG32((base) + 0x34)
#define UART_BLR(base)              HWREG32((base) + 0x38)
#define UART_UASR(base)             HWREG32((base) + 0x38)
#define UART_ACREG(base)            HWREG32((base) + 0x3C)
#define UART_SCR(base)              HWREG32((base) + 0x40)
#define UART_SSR(base)              HWREG32((base) + 0x44)
#define UART_EBLR(base)             HWREG32((base) + 0x48)
#define UART_MVR(base)              HWREG32((base) + 0x50)
#define UART_SYSC(base)             HWREG32((base) + 0x54)
#define UART_SYSS(base)             HWREG32((base) + 0x58)
#define UART_WER(base)              HWREG32((base) + 0x5C)
#define UART_CFPS(base)             HWREG32((base) + 0x60)
#define UART_RXFIFO_LVL(base)       HWREG32((base) + 0x64)
#define UART_TXFIFO_LVL(base)       HWREG32((base) + 0x68)
#define UART_IER2(base)             HWREG32((base) + 0x6C)
#define UART_ISR2(base)             HWREG32((base) + 0x70)
#define UART_FREQ_SEL(base)         HWREG32((base) + 0x74)
#define UART_MDR3(base)             HWREG32((base) + 0x80)
#define UART_TX_DMA_THRESHOLD(base) HWREG32((base) + 0x84)

#define UART_FCR_RX_FIFO_TRIG_MASK (BIT_7 | BIT_6)
#define UART_FCR_RX_FIFO_TRIG_SHFT  6
#define UART_FCR_TX_FIFO_TRIG_MASK (BIT_5 | BIT_4)
#define UART_FCR_TX_FIFO_TRIG_SHFT  4
#define UART_FCR_DMA_MODE           BIT_3
#define UART_FCR_TX_FIFO_CLEAR      BIT_2
#define UART_FCR_RX_FIFO_CLEAR      BIT_1
#define UART_FCR_FIFO_EN            BIT_0

#define UART_LCR_DIV_EN            BIT_7
#define UART_LCR_BREAK_EN          BIT_6
#define UART_LCR_PARITY_TYPE2      BIT_5
#define UART_LCR_PARITY_TYPE1      BIT_4
#define UART_LCR_PARITY_EN         BIT_3
#define UART_LCR_NB_STOP           BIT_2
#define UART_LCR_CHAR_LENGTH(val) ((val) & 0x3)

#define UART_LSR_RXFIFOSTS          BIT_7
#define UART_LSR_TXSRE              BIT_6
#define UART_LSR_TXFIFOE            BIT_5
#define UART_LSR_RXBI               BIT_4
#define UART_LSR_RXFE               BIT_3
#define UART_LSR_RXPE               BIT_2
#define UART_LSR_RXOE               BIT_1
#define UART_LSR_RXFIFOE            BIT_0

#define UART_EFR_AUTOCTSEN          BIT_7
#define UART_EFR_AUTORTSEN          BIT_6
#define UART_EFR_SPECIALCHARDETECT  BIT_5
#define UART_EFR_ENHANCEDEN         BIT_4
#define UART_EFR_SWFLOWCONTROL_MASK 0xF
#define UART_EFR_SWFLOWCONTROL_SHFT 0

#define UART_MCR_TCRTLR     BIT_6
#define UART_MCR_XONEN      BIT_5
#define UART_MCR_LOOPBACKEN BIT_4
#define UART_MCR_CDSTSCH    BIT_3
#define UART_MCR_RISTSCH    BIT_2
#define UART_MCR_RTS        BIT_1
#define UART_MCR_DTR        BIT_0

#define UART_TLR_RX_FIFO_TRIG_MASK 0xF0
#define UART_TLR_RX_FIFO_TRIG_SHFT 4
#define UART_TLR_TX_FIFO_TRIG_MASK 0x0F
#define UART_TLR_TX_FIFO_TRIG_SHFT 0

#define UART_SCR_RX_TRIG_GRANU1 BIT_7
#define UART_SCR_TX_TRIG_GRANU1 BIT_6

#define UART_DLL_CLOCK_LSB(val) ((val) & 0xff)
#define UART_DLH_CLOCK_MSB(val) (((val) >> 8) & 0x3f)

enum {
    UART_MDR1_MODE_16X = 0,
    UART_MDR1_MODE_SIR,
    UART_MDR1_MODE_16X_AUTO_BAUD,
    UART_MDR1_MODE_13X,
    UART_MDR1_MODE_MIR,
    UART_MDR1_MODE_FIR,
    UART_MDR1_MODE_CIR,
    UART_MDR1_MODE_DISABLE,
};
#define UART_MDR1_MODESELECT(val) ((val) & 0x7)

/*********************** MMC/SD MODULE ****************************************/
#define MMC0_BASE_ADDR 0x48060000

#define SD_SYSCONFIG(base)      HWREG32((base) + 0x110)
#define SD_SYSSTATUS(base)      HWREG32((base) + 0x114)
#define SD_CSRE(base)           HWREG32((base) + 0x124)
#define SD_SYSTEST(base)        HWREG32((base) + 0x128)
#define SD_CON(base)            HWREG32((base) + 0x12C)
#define SD_PWCNT(base)          HWREG32((base) + 0x130)
#define SD_SDMASA(base)         HWREG32((base) + 0x200)
#define SD_BLK(base)            HWREG32((base) + 0x204)
#define SD_ARG(base)            HWREG32((base) + 0x208)
#define SD_CMD(base)            HWREG32((base) + 0x20C)
#define SD_RSP10(base)          HWREG32((base) + 0x210)
#define SD_RSP32(base)          HWREG32((base) + 0x214)
#define SD_RSP54(base)          HWREG32((base) + 0x218)
#define SD_RSP76(base)          HWREG32((base) + 0x21C)
#define SD_DATA(base)           HWREG32((base) + 0x220)
#define SD_PSTATE(base)         HWREG32((base) + 0x224)
#define SD_HCTL(base)           HWREG32((base) + 0x228)
#define SD_SYSCTL(base)         HWREG32((base) + 0x22C)
#define SD_STAT(base)           HWREG32((base) + 0x230)
#define SD_IE(base)             HWREG32((base) + 0x234)
#define SD_ISE(base)            HWREG32((base) + 0x238)
#define SD_AC12(base)           HWREG32((base) + 0x23C)
#define SD_CAPA(base)           HWREG32((base) + 0x240)
#define SD_CUR_CAPA(base)       HWREG32((base) + 0x248)
#define SD_FE(base)             HWREG32((base) + 0x250)
#define SD_ADMAES(base)         HWREG32((base) + 0x254)
#define SD_ADMASAL(base)        HWREG32((base) + 0x258)
#define SD_ADMASAH(base)        HWREG32((base) + 0x25C)
#define SD_REV(base)            HWREG32((base) + 0x2FC)

#define SD_SYSCONFIG_AUTOIDLE           BIT_0
#define SD_SYSCONFIG_SOFTRESET          BIT_1
#define SD_SYSCONFIG_ENAWAKEUP          BIT_2
#define SD_SYSCONFIG_SIDLEMODE(val)     (((val) & 0x3) <<  3)
#define SD_SYSCONFIG_CLOCKACTIVITY(val) (((val) & 0x3) <<  8)
#define SD_SYSCONFIG_STANDBYMODE(val)   (((val) & 0x3) << 12)

#define SD_SYSSTATUS_RESETDONE          BIT_0

#define SD_CON_OD               BIT_0
#define SD_CON_INIT             BIT_1
#define SD_CON_HR               BIT_2
#define SD_CON_STR              BIT_3
#define SD_CON_MODE             BIT_4
#define SD_CON_DW8              BIT_5
#define SD_CON_MIT              BIT_6
#define SD_CON_CDP              BIT_7
#define SD_CON_WPP              BIT_8
#define SD_CON_DVAL(val)        (((val) & 0x3) << 9)
#define SD_CON_CTPL             BIT_11
#define SD_CON_CEATA            BIT_12
#define SD_CON_PADEN            BIT_15
#define SD_CON_CLKEXTFREE       BIT_16
#define SD_CON_BOOT_ACK         BIT_17
#define SD_CON_BOOT_CF0         BIT_18
#define SD_CON_DDR              BIT_19
#define SD_CON_DMA_MnS          BIT_20
#define SD_CON_SDMA_LnE         BIT_21

#define SD_SYSCTL_ICE       BIT_0
#define SD_SYSCTL_ICS       BIT_1
#define SD_SYSCTL_CEN       BIT_2
#define SD_SYSCTL_CLKD(val) (((val) & 0x3ff) <<  6)
#define SD_SYSCTL_DTO(val)  (((val) & 0x00f) << 16)
#define SD_SYSCTL_SRA       BIT_24
#define SD_SYSCTL_SRC       BIT_25
#define SD_SYSCTL_SRD       BIT_26

#define SD_HCTL_DTW         BIT_1
#define SD_HCTL_HSPE        BIT_2
#define SD_HCTL_DMAS(val)  (((val) & 0x3) << 3)
#define SD_HCTL_CDTL        BIT_6
#define SD_HCTL_CDSS        BIT_7
#define SD_HCTL_SDBP        BIT_8
#define SD_HCTL_SDVS(val)  (((val) & 0x7) << 9)
#define SD_HCTL_SBGR        BIT_16
#define SD_HCTL_CR          BIT_17
#define SD_HCTL_RWC         BIT_18
#define SD_HCTL_IBG         BIT_19
#define SD_HCTL_IWE         BIT_24
#define SD_HCTL_INS         BIT_25
#define SD_HCTL_REM         BIT_26
#define SD_HCTL_OBWE        BIT_27

#define SD_BLK_NBLK(val)    (((val) & 0xffff) << 16)
#define SD_BLK_BLEN(val)    (((val) & 0x0fff) <<  0)

#define SD_CAPA_TCF(base)   ((SD_CAPA(base) >>  0) & 0x3f)
#define SD_CAPA_TCU         BIT_7
#define SD_CAPA_BCF(base)   ((SD_CAPA(base) >>  8) & 0x3f)
#define SD_CAPA_MBL(base)   ((SD_CAPA(base) >> 16) & 0x03)
#define SD_CAPA_AD2S        BIT_19
#define SD_CAPA_HSS         BIT_21
#define SD_CAPA_DS          BIT_22
#define SD_CAPA_SRS         BIT_23
#define SD_CAPA_VS33        BIT_24
#define SD_CAPA_VS30        BIT_25
#define SD_CAPA_VS18        BIT_26
#define SD_CAPA_64BIT       BIT_28

#define SD_STAT_BADA        BIT_29
#define SD_STAT_CERR        BIT_28
#define SD_STAT_ADMAE       BIT_25
#define SD_STAT_ACE         BIT_24
#define SD_STAT_DEB         BIT_22
#define SD_STAT_DCRC        BIT_21
#define SD_STAT_DTO         BIT_20
#define SD_STAT_CIE         BIT_19
#define SD_STAT_CEB         BIT_18
#define SD_STAT_CCRC        BIT_17
#define SD_STAT_CTO         BIT_16
#define SD_STAT_ERRI        BIT_15
#define SD_STAT_BSR         BIT_10
#define SD_STAT_OBI         BIT_9
#define SD_STAT_CIRQ        BIT_8
#define SD_STAT_CREM        BIT_7
#define SD_STAT_CINS        BIT_6
#define SD_STAT_BRR         BIT_5
#define SD_STAT_BWR         BIT_4
#define SD_STAT_DMA         BIT_3
#define SD_STAT_BGE         BIT_2
#define SD_STAT_TC          BIT_1
#define SD_STAT_CC          BIT_0
#endif
